# Generated by Django 3.0 on 2021-01-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_allproduct_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproduct',
            name='imageurl',
        ),
    ]
