# Generated by Django 3.0 on 2021-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210202_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='unit',
            field=models.CharField(default='หน่วย', max_length=200),
        ),
    ]
